### ISSUE TITLE
只能用一次就'result'了？

### ISSUE THREAD

**Issue by Cxyofficial** [Noctulus/nonebot-plugin-ernie#2]
![Screenshot_2023-09-15-19-32-27-792_com.tencent.mobileqq-edit.jpg](https://github.com/Noctulus/nonebot-plugin-ernie/assets/127767886/b1ea1967-e710-4bd1-8207-938aeb9b08fc)

**Comment by Noctulus** [comment]
需要在千帆大模型内开通计费服务才可使用相关API
